foreground            #e6e1e2
background            #141314
selection_foreground  #332f36
selection_background  #ccc4cd
url_color             #ccc6b8
cursor                #ccc4cd
cursor_text_color     #332f36

color0   #141314
color1   #ffb4ab
color2   #ccc4cd
color3   #ccc6b8
color4   #ccc4cd
color5   #ccc6b8
color6   #0e0c05
color7   #e6e1e2

color8   #948f95
color9   #ffb4ab
color10  #ccc4cd
color11  #ccc6b8
color12  #ccc4cd
color13  #ccc6b8
color14  #0e0c05
color15  #e6e1e2

tab_bar_background              #141314
tab_bar_margin_color            #141314
active_tab_foreground           #332f36
active_tab_background           #ccc4cd
inactive_tab_foreground         #cbc5ca
inactive_tab_background         #141314
